# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Introduction to Data Science
tagline:             'Course Project Website'
description:         'Course Project Website'
url:                 http://titu1994.github.io
baseurl:             '/IDS-Course-Project'
paginate:            5

# About/contact
author:
  name:
  url:
  email:

# Custom vars
version:             1.0.0
