# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Project Alethea
tagline:             ''
description:         'Course Project Website'
url:                 https://titu1994.github.io/
baseurl:             '/IDS-Course-Project'
paginate:            1

pages_list:
  About: 'https://titu1994.github.io/IDS-Course-Project/about'
  Archive: 'https://titu1994.github.io/IDS-Course-Project/archive'
  Feed: 'https://titu1994.github.io/IDS-Course-Project/atom.xml'


# About/contact
author:
  name:
  url:
  email:

# Custom vars
version:             1.0.0
